// Données statiques extraites de main.js

const FAMOUS_STREET_NAMES = new Set([
    'la canebière',
    'quai du port',
    'rue de la république',
    'quai des belges',
    'quai de rive-neuve',
    'rue paradis',
    'corniche du président john fitzgerald kennedy',
    'avenue du prado',
    'place du général de gaulle',
    'boulevard michelet',
    'boulevard rabatau',
    'route de la gineste',
    'allée léon gambetta',
    'boulevard de la corderie',
    'cours pierre puget',
    'rue saint-ferréol',
    'rue de rome',
    'cours lieutaud',
    'place castellane',
    'boulevard baille',
    'boulevard chave',
    'boulevard longchamp',
    'boulevard d\'athènes',
    'rue de lodi',
    'cours julien',
    'place notre-dame du mont',
    'place jean jaurès',
    'boulevard sakakini',
    'rue du camas',
    'boulevard de la libération – général de monsabert',
    'boulevard des dames',
    'place de lenche',
    'rue du panier',
    'place de la major',
    'place de la joliette',
    'place bernard cadenat',
    'cours belsunce',
    'rue d\'aix',
    'avenue camille pelletan',
    'place jules guesde',
    'boulevard national',
    'avenue roger salengro',
    'rue de lyon',
    'boulevard de plombières',
    'avenue du maréchal foch',
    'chemin du littoral',
    'place du marché des capucins',
    'place sébastopol',
    'boulevard périer',
    'boulevard vauban',
    'rond-point du prado',
    'place de la préfecture',
    'cours d\'estienne d\'orves',
    'place aux huiles',
    'rue d\'endoume',
    'chemin du roucas blanc',
    'rue belle de mai',
    'avenue de saint-antoine',
    'plage de l\'estaque',
    'avenue de la pointe rouge',
    'boulevard de la blancarde',
    'avenue des chartreux',
    'avenue de la rose',
    'chemin de morgiou',
    'avenue de mazargues',
    'chemin de la madrague ville',
    'avenue de la capelette',
    'avenue des caillols',
    'boulevard de saint-loup',
    'boulevard de saint-marcel',
    'avenue de saint-barnabé',
    'rue saint-pierre',
    'rue d\'aubagne',
    'rue des catalans',
    'autoroute est',
    'l2 est',
    'l2 nord',
    'autoroute du littoral',
    'tunnel du vieux-port',
    'autoroute du soleil',
    'tunnel du prado carénage',
    'tunnel prado-carénage'
]);

// Rues principales de Marseille (en minuscules)
const MAIN_STREET_NAMES = new Set([
    'rue de la république',
    'la canebière',
    'avenue robert schuman',
    'quai des belges',
    'quai de rive-neuve',
    'boulevard des dames',
    'cours julien',
    'cours lieutaud',
    'cours jean ballard',
    'rue breteuil',
    'rue sainte',
    'rue saint-ferréol',
    'rue paradis',
    'rue de rome',
    'cours pierre puget',
    'place jean jaurès',
    'place castellane',
    'avenue du prado',
    'rond-point du prado',
    'boulevard michelet',
    'boulevard rabatau',
    'avenue jules cantini',
    'boulevard baille',
    'boulevard chave',
    'allée léon gambetta',
    'boulevard jean moulin',
    'boulevard sakakini',
    'boulevard françoise duparc',
    'boulevard national',
    'boulevard de plombières',
    'avenue alexandre fleming',
    'boulevard du maréchal juin',
    'corniche du président john fitzgerald kennedy',
    'boulevard de la corderie',
    'avenue de la corse',
    'boulevard charles livon',
    'rue des catalans',
    'place aux huiles',
    'rue saint-pierre',
    'boulevard schloesing',
    'boulevard romain rolland',
    'boulevard de sainte-marguerite',
    'avenue de mazargues',
    'promenade georges pompidou',
    'avenue pierre mendès france',
    'cours belsunce',
    'cours saint-louis',
    'place jules guesde',
    'place des marseillaises',
    'boulevard camille flammarion',
    'avenue des chutes lavie',
    'boulevard périer',
    'rue d\'endoume',
    'place du 4 septembre',
    'place de la corderie henri bergasse',
    'boulevard notre-dame',
    'boulevard vauban',
    'rue du bois sacré',
    'boulevard de paris',
    'boulevard de strasbourg',
    'place de lenche',
    'place de la major',
    'rue colbert',
    'rue grignan',
    'rue d\'aubagne',
    'boulevard garibaldi',
    'rue de lodi',
    'rue du rouet',
    'avenue du maréchal foch',
    'avenue des chartreux',
    'boulevard de la blancarde',
    'place sébastopol',
    'cours joseph thierry',
    'place notre-dame-du-mont',
    'place félix baret',
    'avenue du cap pinède',
    'avenue roger salengro',
    'boulevard du capitaine gèze',
    'avenue des aygalades',
    'avenue de toulon',
    'boulevard bompard',
    'avenue de hambourg',
    'boulevard charles moretti',
    'avenue viton',
    'boulevard de la gaye',
    'rue de lyon',
    'boulevard jeanne d\’arc',
    'avenue de la capelette',
    'boulevard fifi turin',
    'boulevard voltaire',
    'avenue de montolivet',
    'avenue de saint-just',
    'avenue jean-paul sartre',
    'boulevard guigou',
    'boulevard de montricher',
    'avenue de la fourragère',
    'avenue camille pelletan',
    'rue émile zola',
    'boulevard ferdinand de lesseps',
    'avenue arnavon',
    'l2 nord',
    'l2 est',
    'boulevard de la maison blanche',
    'avenue de saint-louis',
    'avenue de la viste',
    'avenue de saint-antoine',
    'rue félix pyat',
    'boulevard danielle casanova',
    'boulevard gay lussac',
    'avenue ibrahim ali',
    'boulevard burel',
    'boulevard philippon',
    'cours franklin roosevelt',
    'square stalingrad',
    'boulevard longchamp',
    'avenue de saint-barnabé',
    'avenue de saint-julien',
    'avenue du 24 avril 1915',
    'rue pierre de béranger',
    'avenue fernandel',
    'avenue des trois lucs',
    'boulevard mireille lauze',
    'chemin de l\'armée d\'afrique',
    'avenue de la timone',
    'boulevard de pont de vivaux',
    'boulevard gaston crémieux',
    'avenue pasteur',
    'boulevard de dunkerque',
    'quai du port',
    'rue d\'aix',
    'avenue général leclerc',
    'chemin saint-jean-du-désert',
    'boulevard dugommier',
    'boulevard d\'athènes',
    'chemin du littoral',
    'avenue de la madrague de montredon',
    'avenue de la croix rouge',
    'avenue de la rose',
    'avenue des olives',
    'avenue des poilus',
    'rue montaigne',
    'place caire',
    'rue alphonse daudet',
    'avenue de valdonne',
    'avenue de saint-jérôme',
    'chemin de château-gombert',
    'boulevard de saint-loup',
    'boulevard de la valbarelle',
    'boulevard de saint-marcel',
    'boulevard de la barasse',
    'boulevard de la millière',
    'avenue de saint-menet',
    'boulevard de la pomme',
    'avenue jean lombard',
    'avenue des peintres roux',
    'route des camoins',
    'route d\'allauch',
    'boulevard du redon',
    'route léon lachamp',
    'route de la gineste',
    'boulevard de la concorde',
    'chemin du roucas-blanc',
    'boulevard georges estrangin',
    'boulevard paul peytral',
    'boulevard louis salvator',
    'rue des trois frères barthélémy',
    'place estrangin pastré',
    'place de la joliette',
    'boulevard eugène pierre',
    'rue du camas',
    'rue loubon',
    'place bernard cadenat',
    'chemin de sainte-marthe',
    'avenue escadrille normandie-niémen',
    'avenue du merlan',
    'chemin de saint-joseph à sainte-marthe',
    'boulevard henri barnier',
    'avenue andré roussin',
    'rue condorcet',
    'rue rabelais',
    'boulevard fenouil',
    'plage de l\'estaque',
    'boulevard lavoisier',
    'place carli',
    'place de la préfecture',
    'place du général de gaulle',
    'place sadi carnot',
    'rond-point du david',
    'boulevard de la liberté',
    'boulevard national',
    'boulevard de strasbourg',
    'avenue de saint-antoine',
    'avenue de la viste',
    'avenue de saint-louis',
    'grand littoral',
    'plan de campagne',
    'cinéma le prado',
    'cinéma le cézanne',
    'mucem',
    'fort saint-jean',
    'jardin du pharo',
    'palais longchamp',
    'basilique notre-dame de la garde',
    'cathédrale de la major',
    'stade vélodrome',
    'cité radieuse',
    'parc borély',
    'parc chanot',
    'plages du prado',
    'vallon des auffes',
    'les goudes',
    'baie des singes',
    'calanque de sormiou',
    'calanque de morgiou',
    'calanque d\'en-vau',
    'calanque de port-miou',
    'île d\'if',
    'château d\'if',
    'archipel du frioul',
    'abbaye saint-victor',
    'vieille charité',
    'porte d\'aix',
    'opéra de marseille',
    'théâtre de la criée',
    'musée d\'histoire de marseille',
    'musée cantini',
    'musée des beaux-arts',
    'muséum d\'histoire naturelle',
    'friche la belle de mai',
    'domaine de luminy',
    'faculté saint-charles',
    'faculté de médecine timone',
    'hôpital de la timone',
    'hôpital nord',
    'hôpital de la conception',
    'hôpital sainte-marguerite',
    'gare saint-charles',
    'aéroport marseille provence',
    'port autonome de marseille',
    'tunnel prado-carénage',
    'tunnel vieux-port',
    'tunnel de la major',
    'autoroute a7',
    'autoroute a50',
    'autoroute a55'
]);

// Liste des monuments (Noms normalisés pour les infobulles)
const MONUMENT_NAMES = new Set([
    "notre-dame de la garde",
    "cathédrale la major",
    "palais longchamp",
    "abbaye saint-victor",
    "fort saint-jean",
    "fort saint-nicolas",
    "chateau d'if",
    "mucem",
    "la vieille charité",
    "stade Vélodrome",
    "cité radieuse le corbusier",
    "opéra de marseille",
    "préfecture des bouches-du-rhône",
    "hôtel de ville",
    "palais du pharo",
    "porte d’aix",
    "église saint-vincent-de-paul (les réformés)",
    "valla des auffes",
    "grotte cosquer (réplique)",
    "jardin des vestiges",
    "musée d'histoire de marseille",
    "musée des beaux-arts",
    "muséum d'histoire naturelle",
    "mac (musée d'art contemporain)",
    "musée cantini",
    "friche la belle de mai",
    "parc borély",
    "parc balnéaire du prado",
    "parc pastré",
    "parc du 26e centenaire",
    "campagne pastré",
    "ile de frioul",
    "ile ratonneau",
    "ile pomegues",
    "calanque de sormiou",
    "calanque de morgiou",
    "calanque d’en-vau",
    "calanque de port-pin",
    "calanque de sugiton",
    "cap croisette",
    "les goudes",
    "fontaine cantini",
    "hopital caroline",
    "hotel de cabre",
    "maison diamantee",
    "maregraphe",
    "monument aux mobiles des bouches-du-rhone",
    "porte de l’orient",
    "palais des arts",
    "pavillon des chutes-lavie",
    "phare du planier",
    "statue de monseigneur de belsunce",
    "villa la palestine",
    "chapelle de Valbelle dite mosquee de l’arsenal des galeres",
    "halle puget",
    "immeuble des docks de la joliette",
    "statue de david",
    "fontaine estrangin",
    "fontaine des danaides",
    "silo d’arenc",
    "caserne du muy",
    "hôtel des postes",
    "gare de la blancarde",
    "villa gaby",
    "pouce de césar",
    "pagode phap-hoa",
    "château valmante",
    "église st-michel du camas",
    "monument à capazza et fondère",
    "palais omnisports",
    "stade vélodrome",
    "académie des sciences, lettres et arts de marseille",
    "château de château-gombert",
    "observatoire de marseille",
    "villa valmer",
    "théâtre sylvain",
    "sémaphore de callelongue",
    "hôtel dieu",
    "arbre de l’espérance",
    "château pastré",
    "monument aux rapatriés",
    "château grand-séminaire",
    "État-Major des marins-pompiers de marseille",
    "château de la reynarde",
    "château régis",
    "château ricard",
    "tour sainte",
    "cité des arts de la rue",
    "centre pénitentiaire des baumettes",
    "couvent levat",
    "friche de la belle-de-mai",
    "château berger",
    "chapelle saint-joseph du redon",
    "cimetière saint-pierre",
    "église saint-vincent-de-paul dite les réformés",
    "église grecque orthodoxe de la dormition de la mère de dieu",
    "tour cma cgm",
    "château de bois-luzy",
    "église saint-barnabé",
    "château forbin",
    "château périer",
    "villa bagatelle",
    "église sainte-eusébie",
    "banque de france",
    "château talabot",
    "église saint-barthélémy",
    "cathédrale apostolique arménienne des saints traducteurs",
    "cinéma l’alhambra",
    "église saint-pierre",
    "église saint-louis",
    "tombeau de camille olive",
    "couvent madeleine rémusat",
    "vestiges du telescaphe des goudes",
    "croix du sommet du massif de marseilleveyre",
    "le dome",
    "hotel du departement",
    "hotel de region",
    "eglise saint-joseph",
    "hotel roux de corse - lycee montgrand",
    "grande synagogue de marseille",
    "temple reforme grignan",
    "monument à gyptis et protis"
]);

// Quartier → arrondissement (étiquette d'affichage)
const ARRONDISSEMENT_PAR_QUARTIER = {
    // 1er arrondissement
    "Belsunce": "1er",
    "Le Chapitre": "1er",
    "Noailles": "1er",
    "Opéra": "1er",
    "Saint-Charles": "1er",
    "Thiers": "1er",

    // 2e arrondissement
    "Arenc": "2e",
    "Grands-Carmes": "2e",
    "Hôtel de Ville": "2e",
    "La Joliette": "2e",

    // 3e arrondissement
    "Belle-de-Mai": "3e",
    "Saint-Lazare": "3e",
    "Saint-Mauront": "3e",
    "La Villette": "3e",

    // 4e arrondissement
    "La Blancarde": "4e",
    "Les Chartreux": "4e",
    "Chutes-Lavie": "4e",
    "Cinq-Avenues": "4e",

    // 5e arrondissement
    "Baille": "5e",
    "Le Camas": "5e",
    "La Conception": "5e",
    "Saint-Pierre": "5e",

    // 6e arrondissement
    "Castellane": "6e",
    "Lodi": "6e",
    "Notre-Dame-du-Mont": "6e",
    "Palais-de-Justice": "6e",
    "Préfecture": "6e",
    "Vauban": "6e",

    // 7e arrondissement
    "Bompard": "7e",
    "Endoume": "7e",
    "Les Îles": "7e",
    "Le Pharo": "7e",
    "Roucas-Blanc": "7e",
    "Saint-Lambert": "7e",
    "Saint-Victor": "7e",

    // 8e arrondissement
    "Bonneveine": "8e",
    "Les Goudes": "8e",
    "Montredon": "8e",
    "Périer": "8e",
    "La Plage": "8e",
    "Pointe Rouge": "8e",
    "Le Rouet": "8e",
    "Sainte-Anne": "8e",
    "Saint-Giniez": "8e",
    "Vieille-Chapelle": "8e",

    // 9e arrondissement
    "Les Baumettes": "9e",
    "Le Cabot": "9e",
    "Carpiagne": "9e",
    "Mazargues": "9e",
    "La Panouse": "9e",
    "Le Redon": "9e",
    "Sainte-Marguerite": "9e",
    "Sormiou": "9e",
    "Vaufrèges": "9e",

    // 10e arrondissement
    "La Capelette": "10e",
    "Menpenti": "10e",
    "Pont-de-Vivaux": "10e",
    "Saint-Loup": "10e",
    "Saint-Tronc": "10e",
    "La Timone": "10e",

    // 11e arrondissement
    "Les Accates": "11e",
    "La Barasse": "11e",
    "Les Camoins": "11e",
    "Éoures": "11e",
    "La Millière": "11e",
    "La Pomme": "11e",
    "Saint-Marcel": "11e",
    "Saint-Menet": "11e",
    "La Treille": "11e",
    "La Valbarelle": "11e",
    "La Valentine": "11e",

    // 12e arrondissement
    "Les Caillols": "12e",
    "La Fourragère": "12e",
    "Montolivet": "12e",
    "Saint-Barnabé": "12e",
    "Saint-Jean-du-Désert": "12e",
    "Saint-Julien": "12e",
    "Les Trois Lucs": "12e",

    // 13e arrondissement
    "Chateau-Gombert": "13e",
    "La Croix Rouge": "13e",
    "Malpassé": "13e",
    "Les Médecins": "13e",
    "Les Mourets": "13e",
    "Les Olives": "13e",
    "Palama": "13e",
    "La Rose": "13e",
    "Saint-Jérôme": "13e",
    "Saint-Just": "13e",
    "Saint-Mitre": "13e",

    // 14e arrondissement
    "Les Arnavaux": "14e",
    "Bon-Secours": "14e",
    "Le Canet": "14e",
    "Le Merlan": "14e",
    "Saint-Barthélémy": "14e",
    "Sainte-Marthe": "14e",
    "Saint-Joseph": "14e",

    // 15e arrondissement
    "Les Aygalades": "15e",
    "Les Borels": "15e",
    "La Cabucelle": "15e",
    "La Calade": "15e",
    "Les Crottes": "15e",
    "La Delorme": "15e",
    "Notre-Dame-Limite": "15e",
    "Saint-Antoine": "15e",
    "Saint-Louis": "15e",
    "Verduron": "15e",
    "La Viste": "15e",

    // 16e arrondissement
    "L'Estaque": "16e",
    "Les Riaux": "16e",
    "Saint-André": "16e",
    "Saint-Henri": "16e"
};
